export const SEGIP_ESTADO_PERSONA_EXISTE = 2;
export const SEGIP_ESTADO_PERSONA_NO_EXISTE = 1;

export const SEGIP_ESTADO_NO_SE_REALIZO_CONSULTA = 0;
export const SEGIP_ESTADO_NO_SE_ENCONTRO_REGISTRO = 1;
export const SEGIP_ESTADO_SE_ENCONTRO_REGISTRO = 2;
export const SEGIP_ESTADO_SE_ENCONTRO_MAS_DE_UN_REGISTRO = 3;
export const SEGIP_ESTADO_REGISTRO_CON_OBSERVACION = 4;

export const DOCUMENTO_IDENTIDAD = 'Cedula de Identidad';
