import { DataSource } from 'typeorm';
import { Seeder } from 'typeorm-extension';
import TipoActoProcesal from '../entities/tipo-acto-procesal.entity';

export class TipoActoProcesalSeeder implements Seeder {
  async run(dataSource: DataSource): Promise<any> {
    const repository = dataSource.getRepository(TipoActoProcesal);

    const data = [
      {
        codigo: 1,
        descripcion: 'Memorial Adhesion a La Apelacion Restringida',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 1,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial Anotacion Preventiva',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 2,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial de cumplimiento de Medidas Sustitutivas',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 3,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial Certificado De Conducta Para Extramuro',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 4,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial De Acción De Libertad',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 5,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial De Explicacion, Complementación y Enmienda',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 6,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial De Acumulación De Procesos Por Conexitud',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 7,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial De Acusación Particular O Querella',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 8,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial De Adhesión a La Acusación Fiscal',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 9,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial De Ampliación De Término De Investigación',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 10,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial De Anticipo De Prueba',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 11,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial De Apelación Incidental',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 12,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial De Apelación Restringida',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 13,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion: 'Memorial De Aplicación De Medida Cautelar Mixta (Con Detenido)',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 14,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion:
          'Memorial De Aplicación De Medida Cautelar Personal (Con detenido)',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 15,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
      {
        codigo: 1,
        descripcion:
          'Memorial De Aplicación De Medida Cautelar Real (Con detenido)',
        plazoResolucion: 24,
        plazoResolucionUnidad: 2,
        plazoContinuo: true,
        plazoComun: true,
        plazoSuspension: 1,
        visibilidad: 2,
        unicoCausa: true,
        unicoSujetoProcesal: true,
        requiereRespuesta: true,
        requiereAgendamiento: true,
        requiereNotificacion: true,
        requiereNotificacionPersonal: true,
        requiereIndividualizacionSujetos: true,
        requiereIndividualizacionDenunciantes: true,
        requiereIndividualizacionDenunciados: true,
        requiereAdjuntos: true,
        conAdjuntos: true,
        conPlantilla: true,
        cantidadValidaciones: 16,
        interoperable: true,
        cambiaEstado: true,
        cambiaEtapa: true,
        ambito: 'amb1',
        idCategoria: 15,
      },
    ];

    for (const element of data) {
      const exist = await repository.findOneBy({
        descripcion: element.descripcion,
      });
      if (!exist) {
        const temporal = repository.create(element);
        await repository.save(temporal);
      }
    }
  }
}
